name: Build, Test and Run

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: darrylwest/ubuntu24-gpp1420:latest

    steps:
    - uses: actions/checkout@v4

    - name: Show Versions
      run: |
        gcc --version
        g++ --version
        cmake --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Run
      run: ${{github.workspace}}/build/tiny-app
